### ISSUE TITLE
BlogPlatform | templates

### ISSUE THREAD

**Issue by mehdi-mirzaie78** [AradArvin/Alireza_Arvin-CW-Maktab98#1]
It is better to have common html files inside BASE_DIR / templates like base.html you can separate navbar from base.html and use {% include 'filename' %} to include navbar.html in base.html.

You should add your application html files inside a template directory of your application something like:
appname/ templates/appname/file.html

this way when you have a lot of html files you don't get confused between all of theses html files

**Comment by AradArvin** [comment]
I understand, thx for the tip.  Its hard but I'm learning to do it.
